# Generated by Django 2.1.3 on 2018-11-07 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='combustivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30, verbose_name='Nome do Combustivel')),
            ],
        ),
        migrations.CreateModel(
            name='departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=30, verbose_name='Nome do Departamento')),
                ('centrocusto', models.CharField(max_length=10, verbose_name='Centro de Custo')),
            ],
        ),
        migrations.CreateModel(
            name='manutencao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descricao', models.CharField(max_length=50, verbose_name='Nome da manutenção')),
            ],
        ),
        migrations.CreateModel(
            name='posto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descricao', models.CharField(max_length=50, verbose_name='Nome do Posto')),
            ],
        ),
        migrations.CreateModel(
            name='responsavel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome do Responsável')),
                ('email', models.CharField(max_length=30, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone Contato')),
                ('linkcnh', models.CharField(max_length=40, verbose_name='Link CNH')),
                ('linkaut', models.CharField(max_length=40, verbose_name='Link Autorização')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veiculos.departamento', verbose_name='Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='tabelacombustivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posto', models.IntegerField(verbose_name='Código posto')),
                ('combustivel', models.IntegerField(verbose_name='Combustível')),
                ('valor', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Valor')),
            ],
        ),
        migrations.CreateModel(
            name='veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=8, verbose_name='Placa')),
                ('tipo', models.CharField(max_length=15, verbose_name='Tipo')),
                ('marcamodelo', models.CharField(max_length=30, verbose_name='Marca/Modelo')),
                ('apelido', models.CharField(max_length=20, verbose_name='Apelido')),
                ('Ano', models.IntegerField(verbose_name='Ano Fabricação')),
                ('modelo', models.IntegerField(verbose_name='Modelo Fabricação')),
                ('cor', models.CharField(max_length=15, verbose_name='Cor')),
                ('combustivel', models.CharField(max_length=30, verbose_name='Combustível')),
                ('cidade', models.CharField(max_length=15, verbose_name='Cidade')),
                ('Odometro', models.IntegerField(verbose_name='Odômetro')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veiculos.responsavel', verbose_name='Responsável')),
            ],
        ),
    ]
