# Generated by Django 2.1.3 on 2018-11-07 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabelacombustivel',
            name='combustivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veiculos.combustivel', verbose_name='Combustivel'),
        ),
        migrations.AlterField(
            model_name='tabelacombustivel',
            name='posto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veiculos.posto', verbose_name='Posto'),
        ),
    ]
