# Generated by Django 2.1.3 on 2018-11-08 12:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0002_auto_20181107_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fantasia', models.CharField(choices=[('FAEF', 'FAEF'), ('FAIP', 'FAIP'), ('FAIT', 'FAIT'), ('EDUVALES', 'EDUVALES')], max_length=10, verbose_name='Fantasia')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome da Empresa')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
            ],
        ),
        migrations.CreateModel(
            name='requisicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=datetime.datetime(2018, 11, 8, 10, 53, 10, 137990))),
                ('km', models.IntegerField(verbose_name='KM atual')),
                ('quantidade', models.IntegerField(blank=True, verbose_name='Quantidade')),
                ('tipoabastecimento', models.CharField(choices=[('TC', 'Completar'), ('LT', 'Litros'), ('LG', 'Litros no Galão'), ('LP', 'Litros Veiculo Professor')], max_length=2, verbose_name='Tipo Abastecimento')),
                ('combustivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veiculos.combustivel', verbose_name='Combustível')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veiculos.empresa', verbose_name='empresa')),
                ('posto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veiculos.posto', verbose_name='posto')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veiculos.responsavel', verbose_name='Responsavel Abastecimento')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veiculos.veiculo', verbose_name='Veiculo')),
            ],
        ),
    ]
