# Generated by Django 2.1.3 on 2018-11-11 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0003_empresa_requisicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsavel',
            name='tipo',
            field=models.CharField(choices=[('U', 'Usuario'), ('M', 'Profissional'), ('P', 'Profissional Especializado')], default=1, max_length=1, verbose_name='Tipo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome da Empresa'),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 11, 15, 32, 5, 592863)),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='tipo',
            field=models.CharField(choices=[('E', 'Exclusivo'), ('C', 'Compartilhado'), ('F', 'Frota'), ('R', 'Restrito')], max_length=1, verbose_name='Tipo'),
        ),
    ]
