# Generated by Django 2.1.3 on 2018-11-11 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0004_auto_20181111_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsavel',
            name='cnhcat',
            field=models.CharField(choices=[('A', 'Moto'), ('B', 'Carro'), ('C', 'Veiculo de carga acima 3,5 Ton'), ('D', 'Veiculo de Passageiros acima de 8 Lugares'), ('E', 'Veiculo com unidade acoplada acima de 6 Ton')], default=1, max_length=2, verbose_name='Categoria CNH '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 11, 15, 34, 17, 528446)),
        ),
    ]
