# Generated by Django 2.1.3 on 2018-11-11 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0005_auto_20181111_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsavel',
            name='linkaut',
        ),
        migrations.RemoveField(
            model_name='responsavel',
            name='linkcnh',
        ),
        migrations.AddField(
            model_name='responsavel',
            name='aut',
            field=models.FileField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responsavel',
            name='cnh',
            field=models.FileField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 11, 17, 33, 1, 213448)),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='cnhcat',
            field=models.CharField(choices=[('A', 'A - Moto'), ('B', 'B - Carro'), ('C', 'C - Veiculo de carga acima 3,5 Ton'), ('D', 'D - Veiculo de Passageiros acima de 8 Lugares'), ('E', 'E - Veiculo com unidade acoplada acima de 6 Ton')], max_length=2, verbose_name='Categoria CNH '),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='marcamodelo',
            field=models.CharField(max_length=40, verbose_name='Marca/Modelo'),
        ),
    ]
