# Generated by Django 2.1.3 on 2018-11-11 23:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0006_auto_20181111_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicao',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 11, 21, 31, 17, 916376)),
        ),
    ]
