# Generated by Django 2.1.3 on 2018-12-05 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0009_auto_20181202_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamento',
            old_name='Nome',
            new_name='nome',
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 5, 14, 55, 34, 825057)),
        ),
    ]
