# Generated by Django 2.1.3 on 2018-11-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=8, verbose_name='Placa')),
                ('tipo', models.CharField(max_length=15, verbose_name='Tipo')),
                ('marcamodelo', models.CharField(max_length=30, verbose_name='Marca/Modelo')),
                ('apelido', models.CharField(max_length=20, verbose_name='Apelido')),
                ('Ano', models.IntegerField(verbose_name='Ano Fabricação')),
                ('modelo', models.IntegerField(verbose_name='Modelo Fabricação')),
                ('cor', models.CharField(max_length=15, verbose_name='Cor')),
                ('combustivel', models.CharField(max_length=15, verbose_name='Combustivel')),
                ('cidade', models.CharField(max_length=15, verbose_name='Cidade')),
                ('responsavel', models.CharField(max_length=15, verbose_name='Responsável')),
                ('Odometro', models.IntegerField(verbose_name='Odômetro')),
            ],
        ),
    ]
