# Generated by Django 2.1.3 on 2018-11-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='responsavel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome do Responsável')),
                ('departamento', models.IntegerField(verbose_name='Departamento')),
                ('email', models.CharField(max_length=30, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone Contato')),
                ('linkcnh', models.CharField(max_length=40, verbose_name='Link CNH')),
                ('linkaut', models.CharField(max_length=40, verbose_name='Link Autorização')),
            ],
        ),
    ]
