# Generated by Django 2.1.3 on 2018-11-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_responsavel'),
    ]

    operations = [
        migrations.CreateModel(
            name='combustivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30, verbose_name='Nome do Combustivel')),
            ],
        ),
        migrations.CreateModel(
            name='departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=30, verbose_name='Nome do Departamento')),
                ('centrocusto', models.CharField(max_length=10, verbose_name='Centro de Custo')),
            ],
        ),
    ]
