# Generated by Django 2.1.3 on 2018-11-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_combustivel_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='posto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descricao', models.CharField(max_length=50, verbose_name='Nome do Posto')),
            ],
        ),
    ]
