# Generated by Django 2.1.3 on 2018-11-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_posto'),
    ]

    operations = [
        migrations.CreateModel(
            name='tabelacombustivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posto', models.IntegerField(verbose_name='Código posto')),
                ('combustivel', models.IntegerField(verbose_name='Combustível')),
                ('valor', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Valor')),
            ],
        ),
    ]
