# Generated by Django 2.1.3 on 2018-11-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tabelacombustivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsavel',
            name='departamento',
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='combustivel',
            field=models.CharField(max_length=30, verbose_name='Combustível'),
        ),
    ]
