# Generated by Django 2.1.3 on 2018-11-06 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181106_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsavel',
            name='departamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.departamento', verbose_name='Departamento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.responsavel', verbose_name='Responsável'),
        ),
    ]
